# Generated by Django 4.1.3 on 2022-12-05 18:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='descriptionCategory',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='lessonmodels',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
