# Generated by Django 4.1.3 on 2022-12-05 22:34

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_category_descriptioncategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodels',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
