# Generated by Django 4.1.3 on 2022-12-05 22:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lessonmodels_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodels',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
